export const salebd = [
  {
    id: 1,
    title: "iPhone 15 Pro",
    description: "El último modelo de Apple con tecnología avanzada.",
    price: 999.99,
    images: ["/asset/sale/1.webp"],
    isNew: true,
  },
  {
    id: 2,
    title: "Lentes de Sol",
    description: "Estilo y protección para tus ojos.",
    price: 49.99,
    images: ["/asset/sale/2.webp"],
    isNew: true,
  },
  {
    id: 3,
    title: "Oculus con Joystick",
    description: "Sumérgete en la realidad virtual.",
    price: 299.99,
    images: ["/asset/sale/3.webp"],
    isNew: true,
  },
  {
    id: 4,
    title: "PS5",
    description: "La consola de última generación de Sony.",
    price: 499.99,
    images: ["/asset/sale/4.webp"],
    isNew: true,
  },
  {
    id: 5,
    title: "Auriculares",
    description: "Disfruta de tu música con calidad de sonido superior.",
    price: 29.99,
    images: ["/asset/sale/5.webp"],
    isNew: true,
  },
  {
    id: 6,
    title: "Micrófono Tipo Podcast",
    description: "Perfecto para grabaciones y streaming.",
    price: 89.99,
    images: ["/asset/sale/6.webp"],
    isNew: true,
  },
  {
    id: 7,
    title: "Auriculares Bluetooth",
    description: "Conectividad inalámbrica para mayor comodidad.",
    price: 39.99,
    images: ["/asset/sale/7.webp"],
    isNew: true,
  },
  {
    id: 8,
    title: "Luces LED de Decoración",
    description: "Crea ambientes únicos con iluminación LED.",
    price: 19.99,
    images: ["/asset/sale/8.webp"],
    isNew: true,
  },
  {
    id: 9,
    title: "Pantalla Ultra HS Curva",
    description: "Resolución increíble y diseño elegante.",
    price: 399.99,
    images: ["/asset/sale/9.webp"],
    isNew: true,
  },
  {
    id: 10,
    title: "Smartwatch",
    description: "Mantente conectado y activo con estilo.",
    price: 149.99,
    images: ["/asset/sale/10.webp"],
    isNew: true,
  },
];